site_name: " "
theme:
  favicon: logo.png
  name: material
  logo: logo.png
  language: pt
  features:
    - navigation.instant
  palette:
    primary: green
    accent: green

extra_css:
  - stylesheets/extra.css

nav:
  - Landing: index.md
  - Documentation: docs.md
  - Running the app: usage.md
  